### ISSUE TITLE
TLS handshake error with http2

### ISSUE THREAD

**Issue by dennisfischer** [barnacs/compy#2]
The newest commit seems to be not working with https connections.
Errors outputed from compy:

```
2016/03/28 15:06:03 http: TLS handshake error from *IP*:54255: EOF
2016/03/28 15:06:03 http: TLS handshake error from *IP*:54256: EOF
2016/03/28 15:06:03 http: TLS handshake error from *IP*:54257: EOF
2016/03/28 15:06:04 http: TLS handshake error from *IP*:54258: EOF
2016/03/28 15:06:04 http: TLS handshake error from *IP*:54259: EOF
2016/03/28 15:06:04 http: TLS handshake error from *IP*:54260: EOF
```
*IP* is hereby my locals computer IP.
With 6dae9bda0cff47633fdae0f6423abfeda61951b8 the same setup was working.
Since a4a691b7b8930633dee879044d7817039356f605 it no longer works.
Chrome shows ERR_SSL_PROTOCOL_ERROR

Command used for running compy:
`./compy -ca ca.crt -cakey ca.key`

**Comment by barnacs** [comment]
Thanks for reporting this.
Looks like I accidentally broke http1 CONNECT requests with the http2 implementation. Should be fixed by f9a6377

Btw, I recommend using http2 (over tls) for the proxy connection, which would be more efficient and secure. I will update the readme with detailed setup instructions soonish.
